# Site settings
title: Keanu Uchida
description: |
  Tech enthusiast

url: https://ucheetah.github.io/

about_title: About Me
projects_title: Home

# User settings
user_description_appendix: |
  Follow along and connect with me if our passions align!
  <hr>
  This site was taken from Louis Rassaby's GitHub [Jekyll][jekyll], and it's hosted for free on [GitHub Pages][gh-pages]. It's open source, so if
  you like it, fork it on [GitHub][github] and make your own version.

  [github]: https://github.com/lrassaby/lrassaby.github.io
  [gh-pages]: https://pages.github.com/
  [jekyll]: https://jekyllrb.com

  <div> Icons made by <a href="https://www.flaticon.com/authors/eucalyp" title="Eucalyp"> Eucalyp </a> from <a href="https://www.flaticon.com/" title="Flaticon">Flaticon</a></div>
  <div> Profle sketch by Louis Sobol 


email: kblairuchida@gmail.com
linkedin: 
github: ucheetah

relevant_tags: ['projects', 'tech']

#resume_url: 
# music_resume_url:

author: Keanu Uchida
author_title: Data 
author_photo: author_photo2.jpeg
user_description_short: Learning and growth are eternal - hoping to document some of that journey here. Recent Physics and Philosophy grad from the University of Toronto. Passionate about data science and data analysis. Always finding corners where the creative meets the analytic. I also love to dance.

## Disqus
# disqus_identifier: rassaby

## Tracker
# google_analytics_id: UA-109461282-1

keywords: 'data science, data analysis, dance, performance, physics, tech'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


plugins:
  - jekyll-feed


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']



include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']
