# Site settings
title: Keanu Uchida
description: |
  Tech enthusiast

url: https://ucheetah.github.io/

about_title: About Me
projects_title: Home

# User settings
user_description_appendix: |

  <b>Credits:</b>
  - Site taken from <b>Louis Rassaby</b>'s GitHub <ins><a href="https://github.com/lrassaby/lrassaby.github.io">Jekyll</a></ins>. It's hosted for free on <ins><a href="https://pages.github.com/">GitHub Pages</a></ins>. It's open source, so if you like it, fork it on <ins><a href="https://github.com/lrassaby/lrassaby.github.io">GitHub</a></ins>.
  - Profile sketch by <b>Louis Sobol</b>.
  - Favicon by <ins><a href="https://www.flaticon.com/authors/eucalyp">Eucalyp</a></ins> from <ins><a href="https://www.flaticon.com/">Flaticon</a></ins>.

  [github]: https://github.com/lrassaby/lrassaby.github.io
  [gh-pages]: https://pages.github.com/
  [jekyll]: https://jekyllrb.com


email: kblairuchida@gmail.com
linkedin: keanu-uchida
github: ucheetah

relevant_tags: ['projects', 'tech']

#resume_url: 
# music_resume_url:

author: Keanu Uchida
author_title: 
author_photo: author_photo2.jpeg
user_description_short: |
  I'm a recent Physics and Philosophy grad from the University of Toronto who's passionate about data science and software.
  
  Excited by the corners where creative and analytic ideas meet. 
  
  I also love to dance.

## Disqus
# disqus_identifier: rassaby

## Tracker
# google_analytics_id: 

keywords: 'data science, data analysis, dance, performance, physics, tech'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


plugins:
  - jekyll-feed


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']



include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']
